// 常見加密貨幣的中英文對照，讓「代號」欄位可以打「比特幣」跳出 BTC，或打「BTC」直接找到。
export const CRYPTO_LIST: { symbol: string; name: string; aliases: string[] }[] = [
  { symbol: "BTC", name: "Bitcoin", aliases: ["比特幣", "比特币"] },
  { symbol: "ETH", name: "Ethereum", aliases: ["以太幣", "以太坊", "以太币"] },
  { symbol: "USDT", name: "Tether", aliases: ["泰達幣", "泰达币"] },
  { symbol: "USDC", name: "USD Coin", aliases: ["美元穩定幣", "美元稳定币"] },
  { symbol: "BNB", name: "BNB", aliases: ["幣安幣", "币安币"] },
  { symbol: "SOL", name: "Solana", aliases: ["索拉納", "索拉纳"] },
  { symbol: "XRP", name: "XRP", aliases: ["瑞波幣", "瑞波币"] },
  { symbol: "ADA", name: "Cardano", aliases: ["艾達幣", "艾达币"] },
  { symbol: "DOGE", name: "Dogecoin", aliases: ["狗狗幣", "狗狗币"] },
  { symbol: "TRX", name: "TRON", aliases: ["波場", "波场"] },
  { symbol: "TON", name: "Toncoin", aliases: ["Ton幣", "ton币"] },
  { symbol: "AVAX", name: "Avalanche", aliases: ["雪崩幣", "雪崩币"] },
  { symbol: "SHIB", name: "Shiba Inu", aliases: ["柴犬幣", "柴犬币"] },
  { symbol: "DOT", name: "Polkadot", aliases: ["波卡幣", "波卡币"] },
  { symbol: "LINK", name: "Chainlink", aliases: ["鏈接幣", "链接币"] },
  { symbol: "BCH", name: "Bitcoin Cash", aliases: ["比特幣現金", "比特币现金"] },
  { symbol: "LTC", name: "Litecoin", aliases: ["萊特幣", "莱特币"] },
  { symbol: "MATIC", name: "Polygon", aliases: ["馬蹄幣", "马蹄币", "多邊形"] },
  { symbol: "UNI", name: "Uniswap", aliases: ["Uniswap"] },
  { symbol: "ATOM", name: "Cosmos", aliases: ["宇宙幣", "宇宙币"] },
  { symbol: "XLM", name: "Stellar", aliases: ["恆星幣", "恒星币"] },
  { symbol: "ETC", name: "Ethereum Classic", aliases: ["以太經典", "以太经典"] },
  { symbol: "NEAR", name: "NEAR Protocol", aliases: ["Near幣", "near币"] },
  { symbol: "APT", name: "Aptos", aliases: ["Aptos幣", "aptos币"] },
  { symbol: "ARB", name: "Arbitrum", aliases: ["Arbitrum幣"] },
  { symbol: "OP", name: "Optimism", aliases: ["Optimism幣"] },
  { symbol: "SUI", name: "Sui", aliases: ["Sui幣"] },
  { symbol: "PEPE", name: "Pepe", aliases: ["佩佩蛙"] },
  { symbol: "FIL", name: "Filecoin", aliases: ["文件幣", "文件币"] },
  { symbol: "ICP", name: "Internet Computer", aliases: ["網際電腦幣", "网际电脑币"] },
  { symbol: "XPL", name: "Plasma", aliases: ["Plasma幣", "plasma币"] },
  { symbol: "WLD", name: "Worldcoin", aliases: ["世界幣", "世界币"] },
  { symbol: "TAO", name: "Bittensor", aliases: [] },
  { symbol: "PENGU", name: "Pudgy Penguins", aliases: [] },
  { symbol: "HYPE", name: "Hyperliquid", aliases: [] },
  { symbol: "ONDO", name: "Ondo", aliases: [] },
  { symbol: "FARTCOIN", name: "Fartcoin", aliases: [] },
  { symbol: "S", name: "Sonic", aliases: [] },
  { symbol: "TRUMP", name: "Official Trump", aliases: [] },
  { symbol: "PYTH", name: "Pyth Network", aliases: [] },
  { symbol: "JUP", name: "Jupiter", aliases: [] },
  { symbol: "RENDER", name: "Render", aliases: ["渲染幣", "渲染币"] },
  { symbol: "SEI", name: "Sei", aliases: [] },
  { symbol: "INJ", name: "Injective", aliases: [] },
];
