// 跟 tw-stocks.ts 一樣的道理：Yahoo Finance 搜尋 API 不支援中文查詢字串，
// 所以常見美股的中文關鍵字（蘋果、微軟…）搜尋用這份本地清單，代號/英文查詢交給 Yahoo Finance。
export const US_STOCKS: { symbol: string; name: string; aliases: string[] }[] = [
  { symbol: "AAPL", name: "Apple Inc.", aliases: ["蘋果", "苹果"] },
  { symbol: "MSFT", name: "Microsoft Corporation", aliases: ["微軟", "微软"] },
  { symbol: "GOOGL", name: "Alphabet Inc. (Google)", aliases: ["谷歌", "字母控股", "Google"] },
  { symbol: "AMZN", name: "Amazon.com, Inc.", aliases: ["亞馬遜", "亚马逊"] },
  { symbol: "NVDA", name: "NVIDIA Corporation", aliases: ["輝達", "英偉達", "英伟达"] },
  { symbol: "META", name: "Meta Platforms, Inc.", aliases: ["臉書", "脸书", "Facebook"] },
  { symbol: "TSLA", name: "Tesla, Inc.", aliases: ["特斯拉"] },
  { symbol: "AVGO", name: "Broadcom Inc.", aliases: ["博通"] },
  { symbol: "ORCL", name: "Oracle Corporation", aliases: ["甲骨文"] },
  { symbol: "NFLX", name: "Netflix, Inc.", aliases: ["網飛", "网飞", "奈飛", "奈飞"] },
  { symbol: "AMD", name: "Advanced Micro Devices, Inc.", aliases: ["超微"] },
  { symbol: "INTC", name: "Intel Corporation", aliases: ["英特爾", "英特尔"] },
  { symbol: "QCOM", name: "Qualcomm Incorporated", aliases: ["高通"] },
  { symbol: "CRM", name: "Salesforce, Inc.", aliases: ["賽富時", "赛富时"] },
  { symbol: "ADBE", name: "Adobe Inc.", aliases: ["奧多比", "奥多比"] },
  { symbol: "IBM", name: "International Business Machines", aliases: ["國際商業機器", "国际商业机器"] },
  { symbol: "UBER", name: "Uber Technologies, Inc.", aliases: ["優步", "优步"] },
  { symbol: "PYPL", name: "PayPal Holdings, Inc.", aliases: ["貝寶", "贝宝"] },
  { symbol: "DIS", name: "The Walt Disney Company", aliases: ["迪士尼"] },
  { symbol: "KO", name: "The Coca-Cola Company", aliases: ["可口可樂", "可口可乐"] },
  { symbol: "PEP", name: "PepsiCo, Inc.", aliases: ["百事", "百事可樂", "百事可乐"] },
  { symbol: "MCD", name: "McDonald's Corporation", aliases: ["麥當勞", "麦当劳"] },
  { symbol: "SBUX", name: "Starbucks Corporation", aliases: ["星巴克"] },
  { symbol: "NKE", name: "NIKE, Inc.", aliases: ["耐吉", "耐克"] },
  { symbol: "WMT", name: "Walmart Inc.", aliases: ["沃爾瑪", "沃尔玛"] },
  { symbol: "COST", name: "Costco Wholesale Corporation", aliases: ["好市多", "开市客"] },
  { symbol: "V", name: "Visa Inc.", aliases: ["威士卡", "威士"] },
  { symbol: "MA", name: "Mastercard Incorporated", aliases: ["萬事達卡", "万事达卡"] },
  { symbol: "JPM", name: "JPMorgan Chase & Co.", aliases: ["摩根大通"] },
  { symbol: "BAC", name: "Bank of America Corporation", aliases: ["美國銀行", "美国银行"] },
  { symbol: "GS", name: "The Goldman Sachs Group, Inc.", aliases: ["高盛"] },
  { symbol: "BRK-B", name: "Berkshire Hathaway Inc.", aliases: ["波克夏", "伯克希爾", "伯克希尔"] },
  { symbol: "JNJ", name: "Johnson & Johnson", aliases: ["嬌生", "强生"] },
  { symbol: "PFE", name: "Pfizer Inc.", aliases: ["輝瑞", "辉瑞"] },
  { symbol: "XOM", name: "Exxon Mobil Corporation", aliases: ["埃克森美孚"] },
  { symbol: "CVX", name: "Chevron Corporation", aliases: ["雪佛龍", "雪佛龙"] },
  { symbol: "BA", name: "The Boeing Company", aliases: ["波音"] },
  { symbol: "T", name: "AT&T Inc.", aliases: ["美國電話電報", "美国电话电报"] },
  { symbol: "VZ", name: "Verizon Communications Inc.", aliases: ["威訊", "威瑞森"] },
  { symbol: "TSM", name: "Taiwan Semiconductor Manufacturing (ADR)", aliases: ["台積電美股", "台积电美股", "台積電ADR"] },
  { symbol: "BABA", name: "Alibaba Group Holding Limited", aliases: ["阿里巴巴"] },
  { symbol: "PDD", name: "PDD Holdings Inc.", aliases: ["拼多多"] },
  { symbol: "SPOT", name: "Spotify Technology S.A.", aliases: ["Spotify"] },
  { symbol: "ABNB", name: "Airbnb, Inc.", aliases: ["愛彼迎", "爱彼迎"] },
  { symbol: "SHOP", name: "Shopify Inc.", aliases: ["Shopify"] },
  { symbol: "COIN", name: "Coinbase Global, Inc.", aliases: ["Coinbase"] },
  { symbol: "PLTR", name: "Palantir Technologies Inc.", aliases: ["Palantir"] },
  { symbol: "SPY", name: "SPDR S&P 500 ETF Trust", aliases: ["標普500ETF", "标普500ETF"] },
  { symbol: "QQQ", name: "Invesco QQQ Trust", aliases: ["納斯達克ETF", "纳斯达克ETF"] },
  { symbol: "VOO", name: "Vanguard S&P 500 ETF", aliases: ["先鋒標普500", "先锋标普500"] },
];
